### PR TITLE
Updates font with official icons from Google.

### PR DESCRIPTION
**Pull request by patrickberkeley**
This should close: https://github.com/johnotander/ember-cli-material-design-icons/issues/8

### CODE REVIEW

**Comment by patrickberkeley** [comment]
Travis says the build is failing, but tests are passing for me locally.

**Comment by johnotander** [comment]
This is awesome, thanks!

Yeah, the tests are failing as a result of the ember-cli and package versions being out of date. I will update those sometime this week to get the build working again.

**Comment by patrickberkeley** [comment]
:+1: Couple things to note:

1. The official icons are somewhat different from what was in this addon before. So applications that update this addon and use non-existent icons will show a missing character.
1. Some of the official icons in their SVG form use both gray and black. I converted this font from the SVGs, so there are a few classes (for example [the battery ones](https://github.com/johnotander/ember-cli-material-design-icons/blob/master/vendor/css/material-icons.css#L225-L240)) that just appear as a their 'full' version. This appears to be consistent with what was in this addon previously.

**Comment by johnotander** [comment]
Both sound reasonable to me. I've just removed some of the added features that the previous icon font had (spin, rotate, etc.). This is CSS that is more appropriate to be included on a per-project basis. I've personally never used any of those features anyway.

I will be working on upgrading the addon's dependencies, adding a view tests, and properly placing the component code into the `ember-cli-material-design-icons` namespace. So, the latest should be published to npm in about an hour. I'll keep you posted.

Thanks again!

**Comment by johnotander** [comment]
Published to npm as `ember-cli-material-design-icons@1.0.0`.

**Comment by patrickberkeley** [comment]
:boom:

**Pull request merged**
